export const recipients = [
  { value: 'mother', label: 'Mother' },
  { value: 'father', label: 'Father' },
  { value: 'son', label: 'Son' },
  { value: 'daughter', label: 'Daughter' },
  { value: 'wife', label: 'Wife' },
  { value: 'husband', label: 'Husband' },
  { value: 'friend', label: 'Friend' },
  { value: 'colleague', label: 'Colleague' },
  { value: 'romantic', label: 'Romantic partner' },
  { value: 'boss', label: 'Boss' },
  { value: 'client', label: 'Client' },
  { value: 'teacher', label: 'Teacher' },
];

export const contextsByRecipient = {
  mother: [
    "I forgot to call on Mother's Day",
    "I missed our weekly family dinner",
    "I said something hurtful during an argument",
    "I neglected to help with household chores",
    "I forgot to thank you for your support",
    "I missed an important family event",
    "I was disrespectful in front of others",
    "I failed to appreciate your sacrifices",
    "I broke a promise to spend time together",
    "I ignored your advice and made a mistake",
  ],
  father: [
    "I forgot Father's Day",
    "I broke a promise to help with a home project",
    "I disrespected your advice",
    "I missed an important family gathering",
    "I failed to show appreciation for your hard work",
    "I was irresponsible with money you lent me",
    "I spoke rudely to you in front of others",
    "I neglected to include you in an important decision",
    "I failed to follow through on a commitment I made to you",
    "I didn't support you during a difficult time",
  ],
  son: [
    "I missed your important school event",
    "I was too harsh in my criticism",
    "I broke a promise to spend time together",
    "I compared you unfairly to others",
    "I failed to listen when you needed to talk",
    "I invaded your privacy",
    "I didn't support your interests or hobbies",
    "I set unrealistic expectations",
    "I failed to acknowledge your achievements",
    "I lost my temper and said hurtful things",
  ],
  daughter: [
    "I forgot your dance recital",
    "I was dismissive of your feelings",
    "I compared you unfairly to others",
    "I failed to support your career choices",
    "I was too controlling of your personal life",
    "I didn't respect your boundaries",
    "I missed an important milestone in your life",
    "I failed to provide emotional support when you needed it",
    "I was judgmental about your relationships",
    "I didn't trust your decision-making abilities",
  ],
  wife: [
    "I forgot our anniversary",
    "I neglected my share of household responsibilities",
    "I was insensitive to your needs",
    "I made an important decision without consulting you",
    "I failed to support your career aspirations",
    "I was emotionally distant during a difficult time",
    "I broke your trust by keeping secrets",
    "I prioritized work over our relationship",
    "I was disrespectful to your family members",
    "I failed to show appreciation for your efforts",
  ],
  husband: [
    "I made an important decision without consulting you",
    "I was unsupportive during a difficult time",
    "I took you for granted",
    "I failed to communicate my feelings effectively",
    "I neglected our relationship in favor of work or hobbies",
    "I was insensitive to your emotional needs",
    "I broke a promise about our financial decisions",
    "I was disrespectful to your friends or family",
    "I failed to acknowledge your contributions to our home",
    "I was inconsiderate of your personal space and time",
  ],
  friend: [
    "I forgot your birthday",
    "I shared a secret you told me in confidence",
    "I bailed on our plans at the last minute",
    "I was unsupportive during your time of need",
    "I made an insensitive joke at your expense",
    "I failed to repay money I borrowed from you",
    "I took credit for your idea",
    "I was judgmental about your life choices",
    "I neglected our friendship when I started a new relationship",
    "I failed to stand up for you when others spoke badly about you",
  ],
  colleague: [
    "I took credit for your work",
    "I missed an important deadline affecting our team",
    "I spoke negatively about you to other coworkers",
    "I failed to communicate important information",
    "I was uncooperative on a group project",
    "I made an inappropriate comment in a meeting",
    "I disrespected your professional boundaries",
    "I failed to support your idea in front of management",
    "I was consistently late to our meetings",
    "I mishandled a client interaction that affected your work",
  ],
  romantic: [
    "I stood you up on a date",
    "I was caught lying about something important",
    "I flirted with someone else",
    "I forgot an important milestone in our relationship",
    "I was emotionally unavailable when you needed support",
    "I broke a promise about our future plans",
    "I was disrespectful to your friends or family",
    "I invaded your privacy by checking your phone",
    "I failed to communicate my feelings, causing misunderstandings",
    "I was insensitive about your insecurities",
  ],
  boss: [
    "I made a costly mistake at work",
    "I was disrespectful during a meeting",
    "I failed to complete an important task",
    "I mishandled a client relationship",
    "I was consistently late to work",
    "I failed to meet project deadlines",
    "I was dishonest about my progress on a project",
    "I undermined your authority in front of the team",
    "I neglected to follow company policies",
    "I failed to communicate important information",
  ],
  client: [
    "I missed our scheduled appointment",
    "I failed to deliver the project on time",
    "I made a significant error in your order",
    "I was unprofessional in our communication",
    "I misquoted the price for our services",
    "I failed to address your concerns promptly",
    "I breached our confidentiality agreement",
    "I neglected to inform you about important changes",
    "I provided incorrect information about our product",
    "I failed to meet the agreed-upon quality standards",
  ],
  teacher: [
    "I cheated on a test",
    "I was disruptive in class",
    "I failed to turn in an important assignment",
    "I plagiarized on a paper",
    "I was disrespectful to you in front of the class",
    "I lied about why I missed class",
    "I failed to participate in group projects",
    "I neglected to follow safety rules in the lab",
    "I damaged school property",
    "I bullied another student in your class",
  ],
};

export const tones = [
  { value: 'formal', label: 'Formal' },
  { value: 'casual', label: 'Casual' },
  { value: 'heartfelt', label: 'Heartfelt' },
  { value: 'professional', label: 'Professional' },
  { value: 'sincere', label: 'Sincere' },
  { value: 'remorseful', label: 'Remorseful' },
  { value: 'humorous', label: 'Humorous' },
  { value: 'apologetic', label: 'Apologetic' },
  { value: 'regretful', label: 'Regretful' },
];
