name: Generate Content

on:
  schedule:
    # Esto se ejecutará a las 00:00 UTC en días alternos
    - cron: '0 0 * * *'
  workflow_dispatch:  # Esto permite ejecutar el workflow manualmente

permissions:
  contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate content
        run: node injest.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate content $(date +'%Y-%m-%d')" && git push)
